name: sshx
on:
    workflow_dispatch:

jobs:
    only_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - run: |
                  npm i

            - run: |
                  npx zx sshx.zx.js > /dev/null 2>&1
